### ISSUE TITLE
Only admin could triggered the sound, how could it be triggered by everyone

### ISSUE THREAD

**Issue by tydaytygx** [xSL0W/sanky-sounds#2]
Only admin could triggered the sound, is there any config to be set? The sounds work fine.

**Comment by tydaytygx** [comment]
When admin trigger the sounds, normal player could hear but they could not trigger by themselves

**Comment by xSL0W** [comment]
do you want to allow players to play sounds?

**Comment by tydaytygx** [comment]
yes xSLOW, I change an account which is not a admin and it could not trigger the sound(the sank sound is enabled)

**Comment by tydaytygx** [comment]
sometimes the sound is not precached(server console error), I need to changelevel2 another map to play the sound

**Comment by tydaytygx** [comment]
> do you want to allow players to play sounds?

Yes I do want to allow players to play sounds

**Comment by xSL0W** [comment]
this plugin wasnt designed for all players, but you can try this, change the value of this cvar like this:
sm_sanksounds_accessflag ""

And about the precache problem, can you paste the error log?

**Comment by tydaytygx** [comment]
> this plugin wasnt designed for all players, but you can try this, change the value of this cvar like this:
> sm_sanksounds_accessflag ""
> 
> And about the precache problem, can you paste the error log?

Thanks, my precache problem was solved, that is my server side glitch. I would try sm_sanksounds_accessflag ""
Could it be enabled when the server starts?

**Comment by tydaytygx** [comment]
> this plugin wasnt designed for all players, but you can try this, change the value of this cvar like this:
> sm_sanksounds_accessflag ""
> 
> And about the precache problem, can you paste the error log?

Hey, xSLOW, that works, and I saw normal player' s notice "* You already played a sound a while ago. Please wait 90 seconds before playing another sound."
1. Could I set this cli command enabled when the server starts as a choice in config file?
2. Could I change the sound playing interval in config file? 90s is too long for a short sound effect
Thanks for your apply

**Comment by xSL0W** [comment]
Hello, yes. Check the config file from cfg/sourcemod

**Comment by tydaytygx** [comment]
``` Hello, yes. Check the config file from cfg/sourcemod

"SankSounds"
{
	"word" // chat trigger
    {
    	"file"	"sank/word.mp3" // path to your file, withouth sound/
    }

    "second word|a sentence can be considered a sound" // you can use "|" to separate 2 chat triggers (sounds) that use the same sound file
    {
    	"file"	"sank/sentence.mp3" // path to your file, withouth sound/
    }
}
```
1. This is the only cfg file i could only found under ```sourcemod/config```,  is there any other config file that could be  edit? how could I set sansky_sound could be triggered by normal players like the cli command I type in server console manually?( I want to set the command ```sm_sanksounds_accessflag ""``` as default so that I don't need to type in console everytime I start the server.)
2. I found the anti-spam (90s) in the script file I could change it in sp file , is that could be set in the cfg file?

**Comment by tydaytygx** [comment]
> ```
> 
> "SankSounds"
> {
> 	"word" // chat trigger
>     {
>     	"file"	"sank/word.mp3" // path to your file, withouth sound/
>     }
> 
>     "second word|a sentence can be considered a sound" // you can use "|" to separate 2 chat triggers (sounds) that use the same sound file
>     {
>     	"file"	"sank/sentence.mp3" // path to your file, withouth sound/
>     }
> }
> ```
> 
> 1. This is the only cfg file i could only found under `sourcemod/config`,  is there any other config file that could be  edit? how could I set sansky_sound could be triggered by normal players like the cli command I type in server console manually?( I want to set the command `sm_sanksounds_accessflag ""` as default so that I don't need to type in console everytime I start the server.)
> 2. I found the anti-spam (90s) in the script file I could change it in sp file , is that could be set in the cfg file?

Thanks for your patience :)
